apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: parking-automation
  namespace: default
  labels:
    app-container: "parking-automation"
  annotations:
    app.oam.dev/description: "Automated parking system with real-time availability and chat interface"
    app.oam.dev/version: "v1.0.0"
spec:
  components:
  # Main parking automation service
  - name: parking-automation
    type: webservice
    properties:
      name: parking-automation
      image: healthidpuaeacr.azurecr.io/parking-automation:latest
      language: python
      framework: fastapi
      port: 8080
      healthPath: /health
      database: postgres
      cache: redis
      repository: parking-automation

  # Reservation service for managing parking reservations
  - name: reservation-service
    type: webservice
    properties:
      name: reservation-service
      image: docker.io/socrates12345/reservation-service:latest
      language: python
      framework: fastapi
      port: 8080
      healthPath: /health
      database: postgres
      cache: redis
      repository: parking-automation

  # Deploy to host cluster (no vCluster topology)
  # This allows immediate deployment without vCluster dependency
